# Generated by Django 5.1.1 on 2024-12-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Email', models.CharField(default='', max_length=40)),
                ('Department', models.CharField(default='', max_length=50)),
                ('Date_of_joining', models.IntegerField(default='')),
            ],
        ),
    ]
